server:
  port: 8888
spring:
  datasource:
    url: "jdbc:mysql://120.79.59.91:3306/wenda?autoReconnect=true&useUnicode=true&characterEncoding=utf8"
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
      prefix: /
  thymeleaf:
    mode: LEGACYHTML5
  mail:
    password: ldfelthjbqvniifa
    username: 1438168658@qq.com
    host: smtp.qq.com
    port: 465
    protocol: smtps
    properties: 
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logbak.xml
#spring.mail.host=smtp.gmail.com #以Gmail为例
#spring.mail.port=587
#spring.mail.username=邮箱用户名
#spring.mail.password=邮箱密码
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#  