server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://120.79.59.91:3306/wenda
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
      prefix: /
  thymeleaf:
    mode: LEGACYHTML5
mybatis:
  config-location: classpath:mybatis-config.xml